spring:
  application:
    name: recipe-service

  datasource:
    url: jdbc:h2:mem:recipe-db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true

logging:
  level:
    org:
      springframework:
        web: DEBUG

hibernate:
  search:
    backend:
      type: lucene

dummyApi:
  recipes:
    url: https://dummyjson.com/recipes
